
@baseUrl = http://localhost:3000
@name = Web Dev Simplified

###

GET {{baseUrl}}/subscribers

###

GET {{baseUrl}}/subscribers/6089ff2132aef917801e41ab

###

POST {{baseUrl}}/subscribers
Content-Type: application/json

{
	"name" : "{{$dotenv USERNAME}}",
	"subscribedToChannel" : "{{name}}"
}

###

DELETE {{baseUrl}}/subscribers/608a02222768c530d8d8b849

###

PATCH {{baseUrl}}/subscribers/6089ff2132aef917801e41ab
Content-Type: application/json

{
	"name" : "Necqui",
	"subscribedToChannel" : "UxTrendz"
}